// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgowkzivjimhzplpqyml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnb3dreml2amltaHpwbHBxeW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDk3MzEsImV4cCI6MjA3MzkyNTczMX0.Iivc8tt045bevHT5Os6wxJ9P0W6lCcDHx6Agzd9azdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});